name: Continuous Integration

on:
  push:
    branches: [ develop, release, main ]
  pull_request:
    branches: [ develop, release, main ]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: HTML Hint validation
        uses: htmlhint/action-htmlhint@v2.4.0
        with:
          source-path: 'src/'

  docker-test-build:
    runs-on: ubuntu-latest
    needs: lint-and-validate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Build Docker Image
        run: |
          docker build -t test-build:latest .
